CREATE TABLE admin_users (id BIGINT AUTO_INCREMENT PRIMARY KEY, email VARCHAR(180) NOT NULL UNIQUE, password_hash VARCHAR(100) NOT NULL);
CREATE TABLE contents (id BIGINT AUTO_INCREMENT PRIMARY KEY, kind VARCHAR(32) NOT NULL, title VARCHAR(180) NOT NULL, summary VARCHAR(500), body LONGTEXT, image_url VARCHAR(1000), published BOOLEAN NOT NULL DEFAULT FALSE, sort_order INT NOT NULL DEFAULT 0, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6));
CREATE INDEX idx_content_public ON contents(kind,published,sort_order);
CREATE TABLE custom_forms (id BIGINT AUTO_INCREMENT PRIMARY KEY, title VARCHAR(180) NOT NULL, description VARCHAR(500), fields_json LONGTEXT, published BOOLEAN NOT NULL DEFAULT FALSE);
CREATE TABLE leads (id BIGINT AUTO_INCREMENT PRIMARY KEY, kind VARCHAR(32) NOT NULL, status VARCHAR(32) NOT NULL, name VARCHAR(120) NOT NULL, email VARCHAR(180) NOT NULL, phone VARCHAR(30) NOT NULL, city VARCHAR(120), message LONGTEXT, details LONGTEXT, form_id BIGINT, consent BOOLEAN NOT NULL, created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6));
CREATE INDEX idx_leads_kind_created ON leads(kind,created_at);
CREATE INDEX idx_leads_status ON leads(status);
CREATE TABLE site_settings (id BIGINT AUTO_INCREMENT PRIMARY KEY, email VARCHAR(180), phone VARCHAR(30), whatsapp VARCHAR(20), city VARCHAR(120), about LONGTEXT);
